version: "3.5"
services:
  reltime_node:
    image: hyperledger/besu:latest
    container_name: "node-3"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/config.toml
    ports:
      - 8547:8547
      - 30305:30305
volumes:
  .:
